version: "3.4"
services:
  web_server:
    command: sh -c "cargo run"
    build:
      context: .
      cache_from:
        - rust:latest
    networks:
      - axum_api
    volumes:
      - ./:/app
    tty: true
    ports:
      - "8888:8888"
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
networks:
  axum_api:
    driver: bridge

volumes:
  postgres_data:
  