version: "3.4"
services:
  web_server:
    # command: sh -c "cargo run --bin web-server"
    build:
      context: .
      cache_from:
        - rust:latest
    networks:
      - axum_api
    volumes:
      - ./:/app
    tty: true
    ports:
      - "8080:8888"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16.0-alpine
    env_file:
      - .env_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - axum_api
networks:
  axum_api:
    driver: bridge

volumes:
  postgres_data:
