name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: Stop and remove previous container
        run: |
          docker compose down || true
          docker rmi lqrl-back:latest || true
      - name: Run server
        run: |
          docker compose up -d
